FROM quay.io/aptible/ubuntu:16.04
# TODO: quay.io/aptible/ubuntu 16.04

RUN apt-get update \
 && apt-get -y install apache2-utils nginx ruby redis-server python python-pip \
    openssl git ca-certificates net-tools netcat curl \
 && rm -rf /var/lib/apt/lists/*

RUN pip install supervisor==3.3.0

ADD bin/install-registry-v1.sh /root/
RUN /root/install-registry-v1.sh

ADD bin/install-registry-v2.sh /root/
RUN /root/install-registry-v2.sh

ADD bin/exit-event-listener /usr/local/bin/
ADD bin/docker-registry-proxy-bootstrap /usr/local/bin/
ADD bin/docker-registry-v1-bootstrap /usr/local/bin/
ADD bin/docker-registry-v2-bootstrap /usr/local/bin/

ADD etc/supervisord.conf /etc/supervisord.conf
ADD etc/redis.conf /etc/redis/redis.conf

# Remove some Nginx files we don't need for the sake of keeping things clean
RUN rm -rf /etc/nginx/sites-enabled /etc/nginx/sites-available /etc/nginx/nginx.conf

ADD etc/nginx.conf.erb /etc/nginx/
ADD etc/registry-v1.conf.erb /etc/nginx/
ADD etc/registry-v2.conf.erb /etc/nginx/

# Tell this image what version of the registry should be served as default
ENV DUALSTACK_DEFAULT v<%= ENV.fetch 'TAG' %>

# BATS tests are run in a container in test.sh, which ensures we don't
# accidentally leave test files laying around.
ADD test /tmp/test
ADD <%= ENV.fetch 'TAG' %>/test /tmp/test

# When running a container from this image, map a directory containing
# docker-registry-proxy.crt and docker-registry-proxy.key to this volume, e.g.,
# "-v /path/to/my/keys:/etc/nginx/ssl"
VOLUME /etc/nginx/ssl
VOLUME /var/lib/nginx
EXPOSE 443

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
